### ISSUE TITLE
Update to latest version (it's missing the tourism revamp)

### ISSUE THREAD

**Issue by MestreLion** [HaemimontGames/SurvivingMars#7]
Code currently published here is missing the Low-G Amusement Park,  Olympus Hotel and Amphitheatre buildings, and has no mention about Satisfaction mechanic. It's missing latest vanilla updates about the tourism revamp, and might contain incorrect data due to balance changes.

Please update the code so we can have a complete, and most importantly _accurate_ data info.

**Comment by ChoGGi** [comment]
Edit: The updated code (rev 1,001,514+) is at https://github.com/surviving-mars/SurvivingMars


~You can check BuildingTemplates (ingame) for the building ids, and use those to search~
~Olympus Hotel = "Hotel"~
~Amphitheatre = "Amphitheater"~
~Low-G Amusement Park = "LowGAmusementPark"~

~You may wish to download the code and manually search, I see lots of satisfaction hits~

**Comment by MestreLion** [comment]
Nice! I didn't know about that updated repository! Is that official too?

Thank you @ChoGGi , for that and for your amazing QoL mods too. I'm still a vanilla console player, but soon will start on PC.

PS: Github's search is good enough for me to find text in code, so far I had no need to clone the repo locally.

**Comment by MestreLion** [comment]
Nice! I didn't know about that updated repository! Is that official too?

Thank you @ChoGGi , for that and for your amazing QoL mods too. I'm still a vanilla console player, but soon will start on PC.

PS: Github's search is good enough for me to find text in code, so far I had no need to clone the repo locally.
